version: '3.8'

networks:
  voting_network:
    driver: bridge
  gitlab-setup_traefik:
    external: true
    name: gitlab-setup_traefik

volumes:
  db_data:
  uploads:
  logs_volume:

services:
  # API Service
  api:
    image: ${API_IMAGE:-gitlab.failx.de/hetzner/voting-tool/api:latest}
    container_name: voting_api_${CI_COMMIT_SHORT_SHA:-latest}
    restart: unless-stopped
    networks:
      - voting_network
      - gitlab-setup_traefik
    volumes:
      - uploads:/app/uploads
      - logs_volume:/app/logs
    environment:
      - NODE_ENV=production
      - ENABLE_JWT=1
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${DOMAIN}
      - DATABASE_HOST=db
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - HOST=${DOMAIN}
      - APP_PORT=4000
      - GRAPHQL_ENDPOINT=/graphql
      - WEBSOCKET_ENDPOINT=/graphql
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.voting-api.rule=Host(`${DOMAIN}`) && (PathPrefix(`/api`) || PathPrefix(`/graphql`) || PathPrefix(`/subscriptions`) || PathPrefix(`/login`) || PathPrefix(`/organizer`) || PathPrefix(`/event/verify-slug`) || PathPrefix(`/zoom`) || PathPrefix(`/media`) || PathPrefix(`/logout`))"
      - "traefik.http.routers.voting-api.priority=100"
      - "traefik.http.routers.voting-api.entrypoints=websecure"
      - "traefik.http.routers.voting-api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.voting-api.service=voting-api@docker"
      - "traefik.http.services.voting-api.loadbalancer.server.port=4000"
      - "traefik.docker.network=gitlab-setup_traefik"
      # WebSocket Support - temporarily disable middleware for debugging
      # - "traefik.http.middlewares.voting-https.headers.customrequestheaders.X-Forwarded-Proto=https"
      # - "traefik.http.routers.voting-api.middlewares=voting-https"


  # Client Service
  client:
    image: ${CLIENT_IMAGE:-gitlab.failx.de/hetzner/voting-tool/client:latest}
    container_name: voting_client_${CI_COMMIT_SHORT_SHA:-latest}
    restart: unless-stopped
    networks:
      - gitlab-setup_traefik
    depends_on:
      - api
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.voting-client.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.voting-client.priority=10"
      - "traefik.http.routers.voting-client-event.rule=Host(`${DOMAIN}`) && PathPrefix(`/event`) && !PathPrefix(`/event/verify-slug`)"
      - "traefik.http.routers.voting-client-event.priority=5"
      - "traefik.http.routers.voting-client-event.service=voting-client"
      - "traefik.http.routers.voting-client-event.entrypoints=websecure"
      - "traefik.http.routers.voting-client-event.tls.certresolver=letsencrypt"
      - "traefik.http.routers.voting-client.entrypoints=websecure"
      - "traefik.http.routers.voting-client.tls.certresolver=letsencrypt"
      - "traefik.http.services.voting-client.loadbalancer.server.port=80"
      - "traefik.docker.network=gitlab-setup_traefik"

  # Database Service
  db:
    image: mariadb:10.11
    container_name: voting_db_${CI_COMMIT_SHORT_SHA:-latest}
    restart: unless-stopped
    networks:
      - voting_network
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/mysql
    command: |
      mysqld
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --max_connections=1500
      --innodb-buffer-pool-size=512M
      --query-cache-size=64M
      --slow-query-log=1
      --long_query_time=2
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

